# Copyright 1999-2016 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.16.9

EAPI=5

MODULE_AUTHOR="SKAJI"
MODULE_VERSION="v3.1.9"


inherit perl-module

DESCRIPTION="CPAN module authoring tool"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="alpha amd64 arm arm64 hppa ia64 m68k mips ppc ppc64 riscv s390 sh sparc x86   ppc-aix amd64-linux arm-linux arm64-linux ppc64-linux x86-linux ppc-macos x86-macos x64-macos m68k-mint sparc-solaris sparc64-solaris x64-solaris x86-solaris x64-winnt x86-winnt x64-cygwin x86-cygwin"
IUSE=""

DEPEND="dev-perl/Test-CPAN-Meta
	dev-perl/Test-PAUSE-Permissions
	>=dev-perl/App-cpanminus-1.704.400
	dev-perl/Module-Runtime
	>=dev-perl/Test-MinimumVersion-Fast-0.04
	dev-perl/Pod-Markdown
	>=dev-perl/Module-CPANfile-1.1004
	dev-perl/Software-License
	dev-perl/File-Copy-Recursive
	dev-perl/Moo
	dev-perl/Config-Identity
	dev-perl/Test-Requires
	>=dev-perl/Module-Build-Tiny-0.39.0
	>=dev-perl/Text-MicroTemplate-0.24
	dev-perl/Module-Build
	dev-perl/URI
	dev-perl/File-Which
	dev-perl/Version-Next
	dev-perl/JSON
	dev-perl/CPAN-Uploader
	dev-perl/Test-Output
	>=dev-perl/TOML-0.97
	dev-perl/File-pushd
	dev-perl/Test-Pod
	>=dev-perl/Data-Section-Simple-0.07
	>=dev-perl/Spellunker-0.4.0
	dev-perl/Try-Tiny
	dev-lang/perl"
